baseURL = "https://l-vamsi-krishna.github.io/"
languageCode = "en-us"
title = "Vamsi Krishna's Blog"
theme = "PaperMod"
enableRobotsTXT = true


[outputs]
    home = ["HTML", "RSS"]

[author]
    name = "Vamsi Krishna"

[services]
  [services.rss]
    limit = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Vamsi Krishna"
    ShowFullTextContent = true
    [params.label]
    icon = "/profile.jpg"
    iconHeight = 30

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 5

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10
[params.analytics.google]
    SiteVerificationTag = "yGk7oNwk_vEJwmSeO2BWkJuX43-6vpgNzWTvjWBL88s"
